### ISSUE TITLE
Infinite working... popup module

### ISSUE THREAD

**Issue by JelteF** [zepheira/exhibit3#55]
In the nobelists demo I found a sorting order that shows a working... popup module that won't dissapear anymore.
This combination is: Discipline, deceased and then relationship. 
I wasn't able to find any other combinations that caused this strange behavior.

**Comment by zepheiryan** [comment]
Thanks for the precise bug report, I've reproduced and will take a look at it.

**Comment by zepheiryan** [comment]
I've added a temporary fix that eliminates the infinite working dialog by special casing the error condition, but it's revealed a deeper bug surrounding sorting and grouping. If you just do the first two sorts, you'll note some of the discipline groups don't include any sub-groups for the deceased sort, which should have values of yes, no, or a missing indicator.  This is incorrect; even if there's only one shared value in the discipline, it should still be displayed as a sub-group.

You'll see with the temporary fix that some of the relationships end up as sub-groups of one another as well, which is obviously wrong.

Once that bug is fixed, the temporary fix for this one should no longer be necessary.
