### ISSUE TITLE
Need Exhibit.ready() method

### ISSUE THREAD

**Issue by karger** [zepheira/exhibit3#59]
Exhibit3 is currently providing a scriptLoaded.exhibit event that is triggered after all exhibits scripts have loaded.  But someone who needs to listen on that event has to use jquery to specify a listener.on('scriptsLoaded.exhibit').  Since jquery is one of the scripts exhibit loads, this makes it impossible to specify a listener for the event until after the event has triggered!

An easy fix would be to include an Exhibit.ready() method in exhibit-api.js that accepts functions and adds them as listeners to scriptsLoaded.exhibit after exhibit-api.js loads jquery.

**Comment by karger** [comment]
actually it appears that in the current version the time-extension is suffering from this specific problem, as I am getting a "$ is not defined" error when I try to load the extension.

**Comment by zepheiryan** [comment]
Load jQuery yourself.  Exhibit isn't intended to be the only thing happening on a page, which is why it won't load jQuery again if you've already done so.  The assumption is that there would be several reasons to load jQuery for your own purposes entirely apart from Exhibit.

I can see the use if Exhibit is the only thing someone is working with in a given context, but getting beyond that makes me think it would be confusing (and also poorly named).  If you'd like to see this feature added, please submit a pull request.

**Comment by karger** [comment]
See my followon comment.  Does time-extension.js work for you?

**Comment by zepheiryan** [comment]
If you think you found a new bug, open a new issue with steps to reproduce.  Please keep the focus in your feature request on the feature itself.  Though for this one it really comes down to you making a pull request.

As for your follow on, yes, it does, locally.
